### PR TITLE
Collab UI and socket setup

### PR DESCRIPTION
**Pull request by cfyjoanna**
- implement collab UI
- real-time collaboration on the code editor works (room-name is hardcoded for now)

TODO to finish M4 (only farisa and christel plz):
- question generation sucks, need to change it to retrieve a random question given a specified complexity (currently it is done in `collab.js` in `useEffect`
- room-name and complexity need to be passed on after the matching service to this page somehow
- let them be able to change the code language (?)
- store the usernames somewhere and prevent users who should not be in the room from being in the room
- `helpers/questionFormatters.js` kinda no longer works because the format of the retrieved Leetcode questions is so scuffed and wonky ☠️ will probably try to change it to adapt to the retrieved format (if there even is one)

NOTE:
- When you load the page, the question might flicker once and the console has a warning about the socket closing before being connected. It's because of React Strict Mode (which is only used in production): https://stackoverflow.com/a/76800843 If you turn it off both issues are solved

### CODE REVIEW

**Review by phyliciachristel — APPROVED** [review]
whatever u say bro lgtm

**Comment by cfyjoanna** [comment]
> whatever u say bro lgtm

more passion more energy bro @phyliciachristel

**Comment by phyliciachristel** [comment]
im sorry this is the sexiest code ive ever seen!!! how did you manage to create such an absolute wonder

**Review by farisanadia — APPROVED** [review]
lgtm

**Pull request merged**
